import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import Button from '@cloudscape-design/components/button';
import Select from '@cloudscape-design/components/select';
import Textarea from '@cloudscape-design/components/textarea';
import Input from '@cloudscape-design/components/input';
import Badge from '@cloudscape-design/components/badge';
import Alert from '@cloudscape-design/components/alert';
import {applyMode,Mode} from '@cloudscape-design/global-styles';
import '@cloudscape-design/global-styles/index.css';
import {Core,Workspace} from '../shared/engine.mjs';
import './styles.css';

const pages=[['playground','◈','Playground'],['knowledge','▤','Knowledge base'],['tools','⌘','Core tools'],['flows','⑂','Workflows'],['batch','▦','Batch processing'],['audit','≋','Audit trail'],['settings','⚙','Connection & JWT']];
const options=[{label:'Local · Document retrieval',value:'retrieval'},{label:'Connected · Local model',value:'model'}];
function App(){
 const [page,setPage]=useState('playground'),[workspace,setWorkspace]=useState(null),[error,setError]=useState(''),[version,refresh]=useState(0);
 const [theme,setTheme]=useState('dark'),[model,setModel]=useState(options[0]),[prompt,setPrompt]=useState('How does sovereign execution work?');
 const [messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[tab,setTab]=useState('chat');
 const [tool,setTool]=useState({label:'Embeddings · 64 dimensions',value:'embed'}),[result,setResult]=useState(null),[steps,setSteps]=useState('normalize,guard,hash');
 const [title,setTitle]=useState(''),[document,setDocument]=useState(''),[query,setQuery]=useState(''),[hits,setHits]=useState([]);
 const [endpoint,setEndpoint]=useState('http://127.0.0.1:5080'),[token,setToken]=useState(''),[connection,setConnection]=useState('Not connected');
 const [command,setCommand]=useState('help'),[history,setHistory]=useState([{command:'sovereign status',output:'Initializing isolated Wasm runtime…'}]);
 const [latency,setLatency]=useState(null);const terminalEnd=useRef(null);
 useEffect(()=>{let alive=true;fetch(`${import.meta.env.BASE_URL}core.wasm`).then(r=>{if(!r.ok)throw Error('Cannot load Wasm core');return r.arrayBuffer()}).then(Core.create).then(core=>{
  if(!alive)return;const w=new Workspace(core);w.ingest('Sovereign execution','Sovereign runs deterministic tools in WebAssembly with no network imports. The browser owns its memory. Knowledge retrieval uses local word histograms and cosine similarity. Model generation requires a separately connected local model server.');
  w.ingest('Memory and trust','The Wasm ABI uses 32-bit offsets, eight-byte aligned allocation and a 16 MiB memory ceiling. JWT verification belongs to the optional .NET service. No signing key is stored in the Pages site.');setWorkspace(w);
  setHistory([{command:'sovereign status',output:'Wasm ready · 0 host imports · 16 MiB ceiling\nType help to list commands.'}]);
 }).catch(e=>setError(e.message));return()=>{alive=false}},[]);
 useEffect(()=>{documentTheme(theme);},[theme]);
 useEffect(()=>{terminalEnd.current?.scrollIntoView({block:'nearest'});},[history]);
 function documentTheme(value){window.document.documentElement.dataset.theme=value;applyMode(value==='dark'?Mode.Dark:Mode.Light);}
 function safely(fn){setError('');try{const value=fn();refresh(v=>v+1);return value}catch(e){setError(e.message)}}
 async function request(path,body){
  const url=new URL(endpoint);if(url.protocol!=='https:'&&!(['127.0.0.1','localhost','[::1]'].includes(url.hostname)&&url.protocol==='http:'))throw Error('Use HTTPS or an HTTP loopback address');
  const response=await fetch(new URL(path,url),{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(60000)});
  if(!response.ok)throw Error(`Service returned ${response.status}: ${await response.text()}`);return response.json();
 }
 async function send(){if(!workspace||!prompt.trim()||busy)return;setError('');setBusy(true);const text=prompt,start=performance.now();setMessages(m=>[...m,{role:'user',text}]);
  try{let answer;if(model.value==='model'){const guard=workspace.run('guard',text);if(guard.value)throw Error('Blocked by the local secret-label rule');answer=await request('/api/invoke',{prompt:text});}else answer=workspace.answer(text);
   setMessages(m=>[...m,{role:'assistant',text:answer.text,blocked:answer.blocked,sources:answer.sources}]);setLatency(performance.now()-start);refresh(v=>v+1);
  }catch(e){setError(e.message)}finally{setBusy(false)}
 }
 function runCli(){if(!workspace)return;safely(()=>{const [cmd,...rest]=command.trim().split(/\s+/),text=rest.join(' ');let out;
  if(cmd==='help')out='status | models | hash TEXT | embed TEXT | guard TEXT | normalize TEXT\nretrieve QUERY | flow TEXT | clear\nCommands run locally. This terminal does not execute shell commands.';
  else if(cmd==='status')out={runtime:'wasm32',imports:0,documents:workspace.documents.length,ticks:workspace.events.length};
  else if(cmd==='models')out=['Document retrieval (local, extractive)', 'Local model server (requires connection)'];
  else if(cmd==='retrieve')out=workspace.retrieve(text);
  else if(cmd==='flow')out=workspace.flow(text,steps.split(',').map(s=>s.trim()));
  else if(cmd==='clear'){setHistory([]);setCommand('');return}
  else out=workspace.run(cmd,text);
  setHistory(h=>[...h,{command,output:typeof out==='string'?out:JSON.stringify(out,null,2)}]);setCommand('');});}
 function exportAudit(){const url=URL.createObjectURL(new Blob([JSON.stringify(workspace.events,null,2)],{type:'application/json'}));const a=window.document.createElement('a');a.href=url;a.download='sovereign-audit.json';a.click();URL.revokeObjectURL(url);}
 const heading=pages.find(p=>p[0]===page)?.[2];
 return <div className="shell">
  <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('playground')}}><span className="brand-mark">S</span><span>SOVEREIGN<small>COMPUTE, ON YOUR TERMS</small></span></a>
   <div className="workspace-label"><span className="status-dot"/> Personal workspace <span className="mini-tag">LOCAL</span></div>
   <div className="nav-caption">BUILD & EXPLORE</div><nav>{pages.map(([id,icon,label])=><button key={id} className={page===id?'nav-item active':'nav-item'} onClick={()=>{setPage(id);setError('')}}><span>{icon}</span>{label}{id==='playground'&&<span className="nav-dot"/>}</button>)}</nav>
   <div className="sidebar-bottom"><div className="runtime-card"><span className="status-dot"/> {workspace?'Engine online':'Loading engine'}<small>Wasm · No AWS connection</small><div className="runtime-line"><i/></div></div><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀ Light appearance':'☾ Dark appearance'}</button><div className="profile"><span className="avatar">SK</span><span>SnapKitty workspace<small>Self-hosted by design</small></span></div></div>
  </aside>
  <div className="main-shell"><header className="topbar"><span>Workspace <b>/</b> <strong>{heading}</strong></span><div><span className="top-status"><span className="status-dot"/> {workspace?'Local runtime ready':'Starting runtime'}</span><a href="https://github.com/SNAPKITTYWEST/Solution1" target="_blank" rel="noreferrer">Repository ↗</a></div></header>
   <main><div className="page-heading"><div><div className="eyebrow">SOVEREIGN / DEVELOPER CONSOLE</div><h1>{heading}</h1><p>{page==='playground'?'A private space to explore, build, and make it yours.':'Your tools. Your data. Explicit execution.'}</p></div><span className="version-pill">v0.1 <span>EARLY ACCESS</span></span></div>
   {error&&<div className="alert"><Alert type="error" dismissible onDismiss={()=>setError('')}>{error}</Alert></div>}
   <div className="mobile-controls"><Select ariaLabel="Mobile execution mode" selectedOption={model} options={options} onChange={({detail})=>setModel(detail.selectedOption)}/><Button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'Light theme':'Dark theme'}</Button></div>
   <div className="stats"><Stat label="EXECUTION" value="Local first" detail="Browser-isolated Wasm" icon="◈"/><Stat label="CORE MEMORY" value="16 MiB" detail="Hard upper bound" icon="▦"/><Stat label="DOCUMENTS" value={workspace?.documents.length??0} detail="In this session" icon="▤"/><Stat label="AUDIT EVENTS" value={workspace?.events.length??0} detail="Deterministic replay seals" icon="≋"/></div>
   {page==='playground'&&<><div className="playground-grid"><section className="panel chat-panel"><div className="panel-header"><div className="tabs"><button className={tab==='chat'?'selected':''} onClick={()=>setTab('chat')}>Conversation</button><button className={tab==='request'?'selected':''} onClick={()=>setTab('request')}>Request JSON</button></div><button className="quiet" onClick={()=>setMessages([])}>Clear session ↺</button></div>
    <div className="chat-body">{tab==='request'?<pre>{JSON.stringify({mode:model.value,prompt,endpoint:model.value==='model'?endpoint:'wasm://local'},null,2)}</pre>:messages.length?messages.map((m,i)=><article className={`message ${m.role}`} key={i}><div className="message-role">{m.role==='user'?'YOU':'◈ SOVEREIGN'}{m.blocked&&' · BLOCKED'}</div><div className="message-text">{m.text}</div>{m.sources?.length>0&&<div className="source-note">{m.sources.length} local source(s) · extractive retrieval</div>}</article>):<div className="welcome"><div className="welcome-symbol">◈</div><h2>Start with a question.<br/><span>Keep the compute yours.</span></h2><p>Explore the sample knowledge base, run deterministic<br className="desktop-break"/> tools, or connect your own model.</p><div className="suggestions">{['How does sovereign execution work?','What are the memory limits?'].map(q=><button key={q} onClick={()=>setPrompt(q)}>{q}<span>↗</span></button>)}</div></div>}</div>
    <div className="composer"><Textarea ariaLabel="Prompt" value={prompt} onChange={({detail})=>setPrompt(detail.value)} rows={3} placeholder="Ask your knowledge base a question…"/><div className="composer-footer"><span><span className="status-dot"/> {model.value==='retrieval'?'Stays in your browser':'Sent to your configured service'}</span><Button variant="primary" loading={busy} disabled={!workspace||!prompt.trim()} onClick={send}>Run prompt ↗</Button></div></div></section>
    <aside className="panel config-panel"><div className="panel-header"><h3>Run configuration</h3><span>⚙</span></div><div className="config-content"><label>Execution mode</label><Select ariaLabel="Execution mode" selectedOption={model} options={options} onChange={({detail})=>setModel(detail.selectedOption)}/><div className="model-note"><span className="tiny-icon">◈</span><div>{model.value==='retrieval'?'Local document engine':'Bring your own model'}<small>{model.value==='retrieval'?'Extractive retrieval · no language model':'OpenAI-compatible localhost server'}</small></div></div><hr/><label>Runtime guarantees</label><ul className="guarantees"><li>✓ Zero Wasm host imports</li><li>✓ Bounded linear memory</li><li>✓ Deterministic state transitions</li><li>✓ Explicit provider connection</li></ul><hr/><label>Last execution</label><div className="kv"><span>Latency</span><strong>{latency===null?'—':`${latency.toFixed(1)} ms`}</strong></div><div className="kv"><span>Seal</span><code>{workspace?.events.at(-1)?.seal??'—'}</code></div><div className="config-footnote">Seals are reproducible checksums, not cryptographic signatures.</div><button className="text-link" onClick={()=>setPage('settings')}>Configure a local model →</button></div></aside></div></>}
   {page==='knowledge'&&<div className="two-columns"><section className="panel padded"><h2>Add a document</h2><p className="muted">Plain text, kept in memory for this session. Maximum 64 KiB per document.</p><label>Title</label><Input ariaLabel="Document title" value={title} onChange={({detail})=>setTitle(detail.value)}/><label>Content</label><Textarea ariaLabel="Document content" rows={9} value={document} onChange={({detail})=>setDocument(detail.value)}/><Button variant="primary" disabled={!workspace} onClick={()=>safely(()=>{workspace.ingest(title,document);setTitle('');setDocument('')})}>Index document</Button><div className="doc-list">{workspace?.documents.map(d=><div key={d.id}><span>▤ {d.title}</span><small>#{d.id} · {d.text.length} characters</small></div>)}</div></section><section className="panel padded"><h2>Retrieve evidence</h2><label>Search query</label><Input ariaLabel="Retrieval query" value={query} onChange={({detail})=>setQuery(detail.value)}/><Button disabled={!workspace} onClick={()=>safely(()=>setHits(workspace.retrieve(query)))}>Search documents</Button>{hits.map(d=><article className="search-hit" key={d.id}><strong>{d.title}</strong><Badge color="blue">{d.score.toFixed(3)}</Badge><p>{d.text}</p></article>)}</section></div>}
   {['tools','flows','batch'].includes(page)&&<div className="two-columns"><section className="panel padded"><h2>{page==='tools'?'Deterministic primitives':page==='flows'?'Compose an execution flow':'Run a local batch'}</h2><p className="muted">{page==='batch'?'One input per line. Every result gets its own audit event.':'The browser and CLI execute the exact same Wasm binary.'}</p>{page==='tools'&&<Select ariaLabel="Core operation" selectedOption={tool} options={[{label:'Embeddings · 64 dimensions',value:'embed'},{label:'FNV-1a checksum',value:'hash'},{label:'Secret-label guard',value:'guard'},{label:'ASCII normalization',value:'normalize'}]} onChange={({detail})=>setTool(detail.selectedOption)}/>}{page==='flows'&&<><label>Steps (comma separated)</label><Input ariaLabel="Flow steps" value={steps} onChange={({detail})=>setSteps(detail.value)}/></>}<label>Input</label><Textarea ariaLabel="Tool input" rows={8} value={prompt} onChange={({detail})=>setPrompt(detail.value)}/><Button variant="primary" disabled={!workspace} onClick={()=>safely(()=>setResult(page==='flows'?workspace.flow(prompt,steps.split(',').map(s=>s.trim())):page==='batch'?prompt.split('\n').filter(Boolean).slice(0,100).map(text=>({text,...workspace.run('embed',text)})):workspace.run(tool.value,prompt)))}>Execute {page==='flows'?'flow':page==='batch'?'batch':'tool'}</Button><p className="muted">The guard detects literal password, secret, and api_key labels. It is not a general content-safety classifier.</p></section><section className="panel padded"><h2>Execution output</h2><pre className="result">{result?JSON.stringify(result,null,2):'Run an operation to inspect its output.'}</pre></section></div>}
   {page==='audit'&&<section className="panel padded"><div className="flex-between"><h2>Session audit trail</h2><Button onClick={exportAudit} disabled={!workspace}>Export JSON</Button></div><p className="muted">Local, volatile event log. FNV seals detect accidental divergence; this is not a tamper-proof ledger.</p><table><thead><tr><th>Tick</th><th>Operation</th><th>Replay seal</th><th>Status</th></tr></thead><tbody>{workspace?.events.map((e,i)=><tr key={i}><td>{e.tick}</td><td>{e.tool}</td><td><code>{e.seal}</code></td><td><Badge color="green">Completed</Badge></td></tr>)}</tbody></table></section>}
   {page==='settings'&&<section className="panel padded settings"><h2>Connect your .NET service</h2><p className="muted">The Pages site never signs JWTs and never stores tokens. Supply a short-lived token issued by your local CLI. GitHub Pages cannot host the .NET process.</p><label>Service URL</label><Input ariaLabel="Service URL" value={endpoint} onChange={({detail})=>setEndpoint(detail.value)}/><label>JWT access token</label><Input ariaLabel="JWT access token" type="password" value={token} onChange={({detail})=>setToken(detail.value)}/><div className="button-row"><Button variant="primary" onClick={async()=>{setError('');try{const data=await request('/api/status');setConnection(`${data.service} · authenticated`)}catch(e){setError(e.message);setConnection('Connection failed')}}}>Test connection</Button><Button onClick={()=>{setToken('');setConnection('Not connected')}}>Forget token</Button></div><p>{connection}</p><pre>dotnet run --project Sovereign.Host -- token\n# In a second terminal with the same SOVEREIGN_JWT_SECRET:\ndotnet run --project Sovereign.Host -- serve</pre><p className="muted">Configure SOVEREIGN_ALLOWED_ORIGIN to this site's origin. Your browser may request local-network permission. Connect a trusted HTTPS service if browser policy blocks loopback access.</p></section>}
   <section className="terminal"><div className="terminal-header"><div><span className="terminal-dots"><i/><i/><i/></span><strong>Local command console</strong><span className="terminal-label">WASM SHELL</span></div><span>⌘ same engine, different interface</span></div><div className="terminal-output">{history.map((h,i)=><div key={i}><div className="terminal-command"><span>sovereign ❯</span> {h.command}</div><pre>{h.output}</pre></div>)}<div ref={terminalEnd}/></div><form onSubmit={e=>{e.preventDefault();runCli()}}><label htmlFor="command">❯</label><input id="command" autoComplete="off" spellCheck="false" value={command} onChange={e=>setCommand(e.target.value)} placeholder="Type help to explore commands"/><button type="submit" disabled={!workspace}>Run ↵</button></form></section>
   <footer><span><span className="status-dot"/> Built to run on your terms.</span><span>Wasm core · C# service · Swift host · Cloudscape UI</span></footer>
  </main></div>
 </div>
}
function Stat({label,value,detail,icon}){return <div className="stat"><div className="stat-label">{label}<span>{icon}</span></div><strong>{value}</strong><small>{detail}</small></div>}
createRoot(document.getElementById('root')).render(<App/>);
